package newsfeed.service;

/**
 * @author ravi.bhatt
 * @version NewsFeedService: NewsFeedService.java, v 1.0 19/06/21 10:31 am ravi.bhatt Exp $$
 *
 * This service is used to create posts and display news feed for a particular user
 */
public interface NewsFeedService {

    /**
     * This method is used to create the post with autogenerated postId , uName and content.
     * @param postId
     * @param uName
     * @param content
     */
    void createPost(String postId,String uName,String content);

    /**
     * This method is used for replying to the particular post by a user.
     * @param postId
     * @param uName
     * @param content
     */
    void replyToPost(String postId,String uName,String content);

    /**
     * This method is used to increment upvote count a particular post.
     * @param postId
     */
    void upVote(String postId);

    /**
     * This method is used to increment downvote count a particular post.
     * @param postId
     */
    void downVote(String postId);

    /**
     * This method is used to show the news feed for the particular user.
     * @param uName
     */
    void showNewsFeed(String uName);

}
